base_url = "https://xfano.github.io"

title = "Chani"

default_language = "en"

theme = "d3c3nt"

generate_feed = true
feed_filename = "atom.xml"

compile_sass = true
minify_html = true

build_search_index = false

[markdown]
highlight_code = true
highlight_theme = "charcoal"
render_emoji = false

external_links_target_blank = true
external_links_no_follow = true

smart_punctuation = true

[extra]
d3_author = "Chani"

d3_nav = [
  { name = "HOME", path = "/" },
  { name = "POSTS", path = "/posts" }
]

d3_icon = "/icon.png"
